-- File: dffa.vhd
-- Generated by MyHDL 0.7
-- Date: Wed Apr 18 05:51:51 2012


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_07.all;

entity dffa is
    port (
        q: out std_logic;
        d: in std_logic;
        clk: in std_logic;
        rst: in std_logic
    );
end entity dffa;


architecture MyHDL of dffa is


begin




DFFA_LOGIC: process (clk, rst) is
begin
    if (rst = '0') then
        q <= '0';
    elsif rising_edge(clk) then
        q <= d;
    end if;
end process DFFA_LOGIC;

end architecture MyHDL;
